name: Tests

on:
  push:
    paths:
      - '**.c'
      - '**.h'
      - '**.bat'
  pull_request:
    paths:
      - '**.c'
      - '**.h'
      - '**.bat'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Cehckout code
      uses: actions/checkout@v2

    - name: Run tests
      run: .\test.bat
      working-directory: tests
